Repository Todotodot/todotodot-extension, pull requests merged in 2022-06, with the labels that each got.

#1 Initial Set-up with webpack and react
  .gitignore
  dist/images/icon128.png
  dist/images/icon16.png
  dist/images/icon32.png
  dist/images/icon48.png
  dist/manifest.json
  dist/popup.html
  dist/popup.js
  dist/popup.js.LICENSE.txt
  package-lock.json
  package.json
  public/manifest.json
  src/popup.html
  src/popup.jsx
  webpack.config.js
  webpack.dev.js
  webpack.prod.js
Labels: 초기설정

#4 Refactor
  .gitignore
  dist/assets/icon128.png
  dist/assets/icon16.png
  dist/assets/icon32.png
  dist/assets/icon48.png
  dist/assets/slime.png
  dist/manifest.json
  dist/popup.html
  dist/popup.js
  public/assets/slime.png
  src/api/api.js
  src/components/GroupInfo.jsx
  src/components/InitialPage.jsx
  src/components/List.jsx
  src/components/NewSth.jsx
  src/components/TodoInfo.jsx
  src/constants/filterMethod.js
Labels: 기능구현, 리팩토링

#5 refactor: Refactor webpack bundling conditions to use dotenv
  .env
  dist/api.js
  dist/errorMessage.js
  dist/globalStyle.js
  dist/interactionMessage.js
  dist/verifyUser.js
  manifest.json
  package-lock.json
  package.json
  src/api/api.js
  src/components/List.jsx
  webpack.config.js
Labels: 리팩토링

#6 test: Add test code
  package-lock.json
  package.json
  public/popup.html
  src/components/InitialPage.jsx
  src/components/List.jsx
  test/InitialPage.test.js
Labels: 테스트코드

#7 docs: Add readme
  README.md
Labels: 문서
